package com.kiyoshi.gui;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        property_popup_menu = new javax.swing.JPopupMenu();
        table_reserve_btn = new javax.swing.JMenuItem();
        table_order_btn = new javax.swing.JMenuItem();
        table_checkout_btn = new javax.swing.JMenuItem();
        table_detail_btn = new javax.swing.JMenuItem();
        header = new javax.swing.JPanel();
        main_dashboard_btn_box = new javax.swing.JPanel();
        dashboard_btn = new javax.swing.JButton();
        main_reserve_btn_box = new javax.swing.JPanel();
        reserve_btn = new javax.swing.JButton();
        main_order_btn_box = new javax.swing.JPanel();
        order_btn = new javax.swing.JButton();
        main_billing_btn_box = new javax.swing.JPanel();
        billing_btn = new javax.swing.JButton();
        main_statistic_btn_box = new javax.swing.JPanel();
        statistic_btn = new javax.swing.JButton();
        main_history_btn_box = new javax.swing.JPanel();
        history_btn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        dashboard_pane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        table_1_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        table_2_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        table_3_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        table_4_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        table_5_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        table_6_btn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        table_7_btn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        table_8_btn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        table_9_btn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        table_10_btn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        table_11_btn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        table_12_btn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        table_13_btn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        table_14_btn = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        table_15_btn = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        table_16_btn = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        table_17_btn = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        table_18_btn = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        table_19_btn = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        table_20_btn = new javax.swing.JButton();
        reserve_pane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        order_pane = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        billing_pane = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        statistic_pane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        history_pane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        footer = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        table_no_box = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        open_menuitem = new javax.swing.JMenuItem();
        save_menuitem = new javax.swing.JMenuItem();
        saveas_menuitem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        statistics_menuitem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        print_menuitem = new javax.swing.JMenuItem();
        printtohtml_menuitem = new javax.swing.JMenuItem();
        page_setup_menuitem = new javax.swing.JMenuItem();
        print_preview_menuitem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exit_program = new javax.swing.JMenuItem();
        edit_menu = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        view_menu = new javax.swing.JMenu();
        toolbar_menuitem = new javax.swing.JCheckBoxMenuItem();
        statusbar_menuitem = new javax.swing.JCheckBoxMenuItem();
        database_menu = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        new_db_menuitem = new javax.swing.JMenuItem();
        del_db_menuitem = new javax.swing.JMenuItem();
        find_db_menuitem = new javax.swing.JMenuItem();
        login_menuitem = new javax.swing.JMenuItem();
        logout_menuitem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        import_menuitem = new javax.swing.JMenu();
        import_csv_menuitem = new javax.swing.JMenuItem();
        export_menuitem = new javax.swing.JMenu();
        export_csv_menuitem = new javax.swing.JMenuItem();
        export_txt_menuitem = new javax.swing.JMenuItem();
        export_sql_menuitem = new javax.swing.JMenuItem();
        folder_menu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        tools_menu = new javax.swing.JMenu();
        search_menuitem = new javax.swing.JMenuItem();
        backup_menuitem = new javax.swing.JMenuItem();
        bookmark_menuitem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        preference_menuitem = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        help_contents_menuitem = new javax.swing.JMenuItem();
        online_docs_menuitem = new javax.swing.JMenuItem();
        keyboard_shortcuts_menuitem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        report_bug_menuitem = new javax.swing.JMenuItem();
        feedback_menuitem = new javax.swing.JMenuItem();
        website_menuitem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        check_for_update_menuitem = new javax.swing.JMenuItem();
        about_menuitem = new javax.swing.JMenuItem();

        table_reserve_btn.setText("Reserve");
        table_reserve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_reserve_btnActionPerformed(evt);
            }
        });
        property_popup_menu.add(table_reserve_btn);

        table_order_btn.setText("Order");
        property_popup_menu.add(table_order_btn);

        table_checkout_btn.setText("Check out");
        property_popup_menu.add(table_checkout_btn);

        table_detail_btn.setText("Detail");
        property_popup_menu.add(table_detail_btn);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/kiyoshi/info"); // NOI18N
        setTitle(bundle.getString("title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(1024, 640));
        setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        setSize(new java.awt.Dimension(1024, 640));

        header.setBackground(new java.awt.Color(102, 0, 102));
        header.setLayout(new java.awt.GridLayout(1, 6));

        main_dashboard_btn_box.setPreferredSize(new java.awt.Dimension(100, 85));
        main_dashboard_btn_box.setLayout(new java.awt.BorderLayout());

        dashboard_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashboard_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/clipboard.png"))); // NOI18N
        dashboard_btn.setText("Dashboard");
        dashboard_btn.setActionCommand("dashboard");
        dashboard_btn.setIconTextGap(8);
        dashboard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_btnActionPerformed(evt);
            }
        });
        main_dashboard_btn_box.add(dashboard_btn, java.awt.BorderLayout.CENTER);

        header.add(main_dashboard_btn_box);

        main_reserve_btn_box.setPreferredSize(new java.awt.Dimension(100, 85));
        main_reserve_btn_box.setLayout(new java.awt.BorderLayout());

        reserve_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reserve_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/triangular_flag_on_post.png"))); // NOI18N
        reserve_btn.setText("Reserve");
        reserve_btn.setActionCommand("reserve");
        reserve_btn.setIconTextGap(8);
        reserve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserve_btnActionPerformed(evt);
            }
        });
        main_reserve_btn_box.add(reserve_btn, java.awt.BorderLayout.CENTER);

        header.add(main_reserve_btn_box);

        main_order_btn_box.setPreferredSize(new java.awt.Dimension(100, 85));
        main_order_btn_box.setLayout(new java.awt.BorderLayout());

        order_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        order_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/hamburger.png"))); // NOI18N
        order_btn.setText("Order");
        order_btn.setActionCommand("order");
        order_btn.setIconTextGap(8);
        order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btnActionPerformed(evt);
            }
        });
        main_order_btn_box.add(order_btn, java.awt.BorderLayout.CENTER);

        header.add(main_order_btn_box);

        main_billing_btn_box.setPreferredSize(new java.awt.Dimension(100, 85));
        main_billing_btn_box.setLayout(new java.awt.BorderLayout());

        billing_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        billing_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/credit_card.png"))); // NOI18N
        billing_btn.setText("Billing");
        billing_btn.setActionCommand("billing");
        billing_btn.setIconTextGap(8);
        billing_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billing_btnActionPerformed(evt);
            }
        });
        main_billing_btn_box.add(billing_btn, java.awt.BorderLayout.CENTER);

        header.add(main_billing_btn_box);

        main_statistic_btn_box.setPreferredSize(new java.awt.Dimension(100, 85));
        main_statistic_btn_box.setLayout(new java.awt.BorderLayout());

        statistic_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statistic_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bar_chart.png"))); // NOI18N
        statistic_btn.setText("Statistic");
        statistic_btn.setActionCommand("statistic");
        statistic_btn.setIconTextGap(8);
        statistic_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistic_btnActionPerformed(evt);
            }
        });
        main_statistic_btn_box.add(statistic_btn, java.awt.BorderLayout.CENTER);

        header.add(main_statistic_btn_box);

        main_history_btn_box.setPreferredSize(new java.awt.Dimension(100, 85));
        main_history_btn_box.setLayout(new java.awt.BorderLayout());

        history_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        history_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/clock4.png"))); // NOI18N
        history_btn.setText("History");
        history_btn.setActionCommand("history");
        history_btn.setIconTextGap(8);
        history_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_btnActionPerformed(evt);
            }
        });
        main_history_btn_box.add(history_btn, java.awt.BorderLayout.CENTER);

        header.add(main_history_btn_box);

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        body.setPreferredSize(new java.awt.Dimension(1024, 434));
        body.setLayout(new java.awt.CardLayout());

        dashboard_pane.setBackground(new java.awt.Color(255, 255, 255));
        dashboard_pane.setLayout(new java.awt.GridLayout(4, 5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        table_1_btn.setBackground(new java.awt.Color(255, 255, 255));
        table_1_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_1_btn.setForeground(new java.awt.Color(51, 204, 0));
        table_1_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_1_btn.setText("Table 1");
        table_1_btn.setToolTipText("Table number");
        table_1_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_1_btn.setDisabledIcon(null);
        table_1_btn.setDisabledSelectedIcon(null);
        table_1_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_1_btn.setIconTextGap(0);
        table_1_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_1_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_1_btnMouseReleased(evt);
            }
        });
        table_1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel1.add(table_1_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        table_2_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_2_btn.setForeground(new java.awt.Color(255, 0, 0));
        table_2_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_2_btn.setText("Mr.Juk");
        table_2_btn.setToolTipText("Table number");
        table_2_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_2_btn.setDisabledIcon(null);
        table_2_btn.setDisabledSelectedIcon(null);
        table_2_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_2_btn.setIconTextGap(0);
        table_2_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel2.add(table_2_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        table_3_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_3_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_3_btn.setText("Table 3");
        table_3_btn.setToolTipText("Table number");
        table_3_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_3_btn.setDisabledIcon(null);
        table_3_btn.setDisabledSelectedIcon(null);
        table_3_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_3_btn.setIconTextGap(0);
        table_3_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel3.add(table_3_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        table_4_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_4_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_4_btn.setText("Table 4");
        table_4_btn.setToolTipText("Table number");
        table_4_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_4_btn.setDisabledIcon(null);
        table_4_btn.setDisabledSelectedIcon(null);
        table_4_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_4_btn.setIconTextGap(0);
        table_4_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel4.add(table_4_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        table_5_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_5_btn.setForeground(new java.awt.Color(255, 0, 51));
        table_5_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_5_btn.setText("Reserved");
        table_5_btn.setToolTipText("Table number");
        table_5_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_5_btn.setDisabledIcon(null);
        table_5_btn.setDisabledSelectedIcon(null);
        table_5_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_5_btn.setIconTextGap(0);
        table_5_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_5_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel5.add(table_5_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        table_6_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_6_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_6_btn.setText("Table 6");
        table_6_btn.setToolTipText("Table number");
        table_6_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_6_btn.setDisabledIcon(null);
        table_6_btn.setDisabledSelectedIcon(null);
        table_6_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_6_btn.setIconTextGap(0);
        table_6_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_6_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel6.add(table_6_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        table_7_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_7_btn.setForeground(new java.awt.Color(0, 204, 51));
        table_7_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_7_btn.setText("Table 7");
        table_7_btn.setToolTipText("Table number");
        table_7_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_7_btn.setDisabledIcon(null);
        table_7_btn.setDisabledSelectedIcon(null);
        table_7_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_7_btn.setIconTextGap(0);
        table_7_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_7_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel7.add(table_7_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.setLayout(new java.awt.BorderLayout());

        table_8_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_8_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_8_btn.setText("Table 8");
        table_8_btn.setToolTipText("Table number");
        table_8_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_8_btn.setDisabledIcon(null);
        table_8_btn.setDisabledSelectedIcon(null);
        table_8_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_8_btn.setIconTextGap(0);
        table_8_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_8_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel8.add(table_8_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel9.setLayout(new java.awt.BorderLayout());

        table_9_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_9_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_9_btn.setText("Table 9");
        table_9_btn.setToolTipText("Table number");
        table_9_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_9_btn.setDisabledIcon(null);
        table_9_btn.setDisabledSelectedIcon(null);
        table_9_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_9_btn.setIconTextGap(0);
        table_9_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_9_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel9.add(table_9_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel10.setLayout(new java.awt.BorderLayout());

        table_10_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_10_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_10_btn.setText("Table 10");
        table_10_btn.setToolTipText("Table number");
        table_10_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_10_btn.setDisabledIcon(null);
        table_10_btn.setDisabledSelectedIcon(null);
        table_10_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_10_btn.setIconTextGap(0);
        table_10_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_10_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel10.add(table_10_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel11.setLayout(new java.awt.BorderLayout());

        table_11_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_11_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_11_btn.setText("Table 11");
        table_11_btn.setToolTipText("Table number");
        table_11_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_11_btn.setDisabledIcon(null);
        table_11_btn.setDisabledSelectedIcon(null);
        table_11_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_11_btn.setIconTextGap(0);
        table_11_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_11_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel11.add(table_11_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel12.setLayout(new java.awt.BorderLayout());

        table_12_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_12_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_12_btn.setText("Table 12");
        table_12_btn.setToolTipText("Table number");
        table_12_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_12_btn.setDisabledIcon(null);
        table_12_btn.setDisabledSelectedIcon(null);
        table_12_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_12_btn.setIconTextGap(0);
        table_12_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_12_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel12.add(table_12_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel13.setLayout(new java.awt.BorderLayout());

        table_13_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_13_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_13_btn.setText("Table 13");
        table_13_btn.setToolTipText("Table number");
        table_13_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_13_btn.setDisabledIcon(null);
        table_13_btn.setDisabledSelectedIcon(null);
        table_13_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_13_btn.setIconTextGap(0);
        table_13_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_13_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel13.add(table_13_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel14.setLayout(new java.awt.BorderLayout());

        table_14_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_14_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_14_btn.setText("Table 14");
        table_14_btn.setToolTipText("Table number");
        table_14_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_14_btn.setDisabledIcon(null);
        table_14_btn.setDisabledSelectedIcon(null);
        table_14_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_14_btn.setIconTextGap(0);
        table_14_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_14_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel14.add(table_14_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel15.setLayout(new java.awt.BorderLayout());

        table_15_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_15_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_15_btn.setText("Table 15");
        table_15_btn.setToolTipText("Table number");
        table_15_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_15_btn.setDisabledIcon(null);
        table_15_btn.setDisabledSelectedIcon(null);
        table_15_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_15_btn.setIconTextGap(0);
        table_15_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_15_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel15.add(table_15_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel16.setLayout(new java.awt.BorderLayout());

        table_16_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_16_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_16_btn.setText("Table 16");
        table_16_btn.setToolTipText("Table number");
        table_16_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_16_btn.setDisabledIcon(null);
        table_16_btn.setDisabledSelectedIcon(null);
        table_16_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_16_btn.setIconTextGap(0);
        table_16_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_16_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel16.add(table_16_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel16);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel18.setLayout(new java.awt.BorderLayout());

        table_17_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_17_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_17_btn.setText("Table 17");
        table_17_btn.setToolTipText("Table number");
        table_17_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_17_btn.setDisabledIcon(null);
        table_17_btn.setDisabledSelectedIcon(null);
        table_17_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_17_btn.setIconTextGap(0);
        table_17_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_17_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel18.add(table_17_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel19.setLayout(new java.awt.BorderLayout());

        table_18_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_18_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_18_btn.setText("Table 18");
        table_18_btn.setToolTipText("Table number");
        table_18_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_18_btn.setDisabledIcon(null);
        table_18_btn.setDisabledSelectedIcon(null);
        table_18_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_18_btn.setIconTextGap(0);
        table_18_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_18_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel19.add(table_18_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel20.setLayout(new java.awt.BorderLayout());

        table_19_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_19_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_19_btn.setText("Table 19");
        table_19_btn.setToolTipText("Table number");
        table_19_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_19_btn.setDisabledIcon(null);
        table_19_btn.setDisabledSelectedIcon(null);
        table_19_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_19_btn.setIconTextGap(0);
        table_19_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_19_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel20.add(table_19_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel20);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel21.setLayout(new java.awt.BorderLayout());

        table_20_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_20_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kiyoshi/ico/bust_in_silhouette.png"))); // NOI18N
        table_20_btn.setText("Table 20");
        table_20_btn.setToolTipText("Table number");
        table_20_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_20_btn.setDisabledIcon(null);
        table_20_btn.setDisabledSelectedIcon(null);
        table_20_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        table_20_btn.setIconTextGap(0);
        table_20_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        table_20_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_btnActionPerformed(evt);
            }
        });
        jPanel21.add(table_20_btn, java.awt.BorderLayout.CENTER);

        dashboard_pane.add(jPanel21);

        body.add(dashboard_pane, "card3");

        jLabel1.setText("jLabel1");

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout reserve_paneLayout = new javax.swing.GroupLayout(reserve_pane);
        reserve_pane.setLayout(reserve_paneLayout);
        reserve_paneLayout.setHorizontalGroup(
            reserve_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserve_paneLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(reserve_paneLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        reserve_paneLayout.setVerticalGroup(
            reserve_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserve_paneLayout.createSequentialGroup()
                .addGroup(reserve_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserve_paneLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(reserve_paneLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        body.add(reserve_pane, "card2");

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout order_paneLayout = new javax.swing.GroupLayout(order_pane);
        order_pane.setLayout(order_paneLayout);
        order_paneLayout.setHorizontalGroup(
            order_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_paneLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jRadioButton1)
                .addContainerGap(630, Short.MAX_VALUE))
        );
        order_paneLayout.setVerticalGroup(
            order_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_paneLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jRadioButton1)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        body.add(order_pane, "card4");

        jButton21.setText("jButton21");

        javax.swing.GroupLayout billing_paneLayout = new javax.swing.GroupLayout(billing_pane);
        billing_pane.setLayout(billing_paneLayout);
        billing_paneLayout.setHorizontalGroup(
            billing_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(billing_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(billing_paneLayout.createSequentialGroup()
                    .addGap(472, 472, 472)
                    .addComponent(jButton21)
                    .addContainerGap(473, Short.MAX_VALUE)))
        );
        billing_paneLayout.setVerticalGroup(
            billing_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(billing_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(billing_paneLayout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(jButton21)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        body.add(billing_pane, "card4");

        statistic_pane.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(32767, 32767));
        jTabbedPane1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel17);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel22);

        statistic_pane.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        body.add(statistic_pane, "card4");

        history_pane.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        history_pane.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        body.add(history_pane, "card4");

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        jTextField3.setText("Status");

        table_no_box.setEditable(false);

        jTextField5.setText("jTextField5");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(table_no_box, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(624, Short.MAX_VALUE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(table_no_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(footer, java.awt.BorderLayout.SOUTH);

        file_menu.setText("File");

        open_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open_menuitem.setText("Open...");
        open_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_menuitemActionPerformed(evt);
            }
        });
        file_menu.add(open_menuitem);

        save_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save_menuitem.setText("Save");
        file_menu.add(save_menuitem);

        saveas_menuitem.setText("Save as...");
        saveas_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveas_menuitemActionPerformed(evt);
            }
        });
        file_menu.add(saveas_menuitem);
        file_menu.add(jSeparator3);

        statistics_menuitem.setLabel("Statistics");
        statistics_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistic_btnActionPerformed(evt);
            }
        });
        file_menu.add(statistics_menuitem);
        file_menu.add(jSeparator7);

        print_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        print_menuitem.setText("Print...");
        file_menu.add(print_menuitem);

        printtohtml_menuitem.setText("Print to HTML");
        file_menu.add(printtohtml_menuitem);

        page_setup_menuitem.setText("Page Setup...");
        file_menu.add(page_setup_menuitem);

        print_preview_menuitem.setText("Print Preview...");
        file_menu.add(print_preview_menuitem);
        file_menu.add(jSeparator2);

        exit_program.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit_program.setText("Exit");
        exit_program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_programActionPerformed(evt);
            }
        });
        file_menu.add(exit_program);

        jMenuBar1.add(file_menu);

        edit_menu.setText("Edit");

        jMenuItem25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem25.setText("Undo");
        jMenuItem25.setEnabled(false);
        edit_menu.add(jMenuItem25);

        jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem26.setText("Redo");
        jMenuItem26.setEnabled(false);
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        edit_menu.add(jMenuItem26);
        edit_menu.add(jSeparator8);

        jMenuItem27.setText("Cut");
        edit_menu.add(jMenuItem27);

        jMenuItem28.setText("Copy");
        edit_menu.add(jMenuItem28);

        jMenuItem30.setText("Paste");
        jMenuItem30.setEnabled(false);
        edit_menu.add(jMenuItem30);

        jMenuItem31.setText("Paste from History");
        jMenuItem31.setEnabled(false);
        edit_menu.add(jMenuItem31);

        jMenuItem33.setText("Delete");
        edit_menu.add(jMenuItem33);

        jMenuItem32.setText("Select All");
        edit_menu.add(jMenuItem32);
        edit_menu.add(jSeparator9);

        jMenuItem36.setText("Find/Replace...");
        edit_menu.add(jMenuItem36);

        jMenuItem34.setText("Find Next");
        edit_menu.add(jMenuItem34);

        jMenuItem35.setText("Find Previous");
        edit_menu.add(jMenuItem35);

        jMenuBar1.add(edit_menu);

        view_menu.setText("View");
        view_menu.setToolTipText("");

        toolbar_menuitem.setSelected(true);
        toolbar_menuitem.setText("Show Toolbar");
        toolbar_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_menuitemActionPerformed(evt);
            }
        });
        view_menu.add(toolbar_menuitem);

        statusbar_menuitem.setSelected(true);
        statusbar_menuitem.setText("Show Status bar");
        statusbar_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusbar_menuitemActionPerformed(evt);
            }
        });
        view_menu.add(statusbar_menuitem);

        jMenuBar1.add(view_menu);

        database_menu.setText("Database");

        jMenu7.setText("Connect..");

        new_db_menuitem.setText("New...");
        jMenu7.add(new_db_menuitem);

        del_db_menuitem.setText("Delete...");
        jMenu7.add(del_db_menuitem);

        find_db_menuitem.setText("Find...");
        jMenu7.add(find_db_menuitem);

        database_menu.add(jMenu7);

        login_menuitem.setText("Login");
        login_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menuitemActionPerformed(evt);
            }
        });
        database_menu.add(login_menuitem);

        logout_menuitem.setText("Logout");
        logout_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuitemActionPerformed(evt);
            }
        });
        database_menu.add(logout_menuitem);
        database_menu.add(jSeparator1);

        import_menuitem.setText("Import...");

        import_csv_menuitem.setText("From CSV");
        import_menuitem.add(import_csv_menuitem);

        database_menu.add(import_menuitem);

        export_menuitem.setText("Export...");

        export_csv_menuitem.setText("To CSV");
        export_menuitem.add(export_csv_menuitem);

        export_txt_menuitem.setText("To TXT");
        export_menuitem.add(export_txt_menuitem);

        export_sql_menuitem.setText("To SQL");
        export_menuitem.add(export_sql_menuitem);

        database_menu.add(export_menuitem);

        jMenuBar1.add(database_menu);

        folder_menu.setText("Folder");

        jMenuItem5.setText("Add...");
        folder_menu.add(jMenuItem5);

        jMenuItem6.setText("Edit...");
        folder_menu.add(jMenuItem6);

        jMenuItem7.setText("Remove...");
        folder_menu.add(jMenuItem7);

        jMenuBar1.add(folder_menu);

        tools_menu.setText("Tools");

        search_menuitem.setText("Search...");
        tools_menu.add(search_menuitem);

        backup_menuitem.setText("Backup");
        tools_menu.add(backup_menuitem);

        bookmark_menuitem.setText("Bookmarks");
        tools_menu.add(bookmark_menuitem);
        tools_menu.add(jSeparator6);

        preference_menuitem.setText("Preference");
        preference_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preference_menuitemActionPerformed(evt);
            }
        });
        tools_menu.add(preference_menuitem);

        jMenuBar1.add(tools_menu);

        help_menu.setText("Help");

        help_contents_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        help_contents_menuitem.setText("Help Contents");
        help_contents_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_contents_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(help_contents_menuitem);

        online_docs_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        online_docs_menuitem.setText("Online Docs and Support");
        online_docs_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                online_docs_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(online_docs_menuitem);

        keyboard_shortcuts_menuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        keyboard_shortcuts_menuitem.setText("Keyboard shortcuts");
        keyboard_shortcuts_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboard_shortcuts_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(keyboard_shortcuts_menuitem);
        help_menu.add(jSeparator5);

        report_bug_menuitem.setText("Report Bug...");
        report_bug_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_bug_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(report_bug_menuitem);

        feedback_menuitem.setText("Feedback...");
        feedback_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(feedback_menuitem);

        website_menuitem.setText("Website..");
        website_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                website_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(website_menuitem);
        help_menu.add(jSeparator4);

        check_for_update_menuitem.setText("Check for Updates");
        check_for_update_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_for_update_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(check_for_update_menuitem);

        about_menuitem.setText("About");
        about_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_menuitemActionPerformed(evt);
            }
        });
        help_menu.add(about_menuitem);

        jMenuBar1.add(help_menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_btnActionPerformed
        setPane(dashboard_pane);
    }//GEN-LAST:event_dashboard_btnActionPerformed

    private void table_1_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_1_btnMouseReleased
        if (evt.isPopupTrigger()) {
            property_popup_menu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_table_1_btnMouseReleased

    private void reserve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserve_btnActionPerformed
        setPane(reserve_pane);
    }//GEN-LAST:event_reserve_btnActionPerformed

    private void open_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_menuitemActionPerformed
//        JFileChooser chooser = new JFileChooser();
//        chooser.showOpenDialog(null);
//        File f = chooser.getSelectedFile();
    }//GEN-LAST:event_open_menuitemActionPerformed

    private void saveas_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveas_menuitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveas_menuitemActionPerformed

    private void exit_programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_programActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_programActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void toolbar_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_menuitemActionPerformed
//        if (evt.getSource().equals(toolbar_menuitem)) {
//            boolean tb_state = toolbar_menuitem.isSelected();
//            int tb_status = 1;
//            if (tb_state == true) {
//                tb_status = 1;
//            }
//            if (tb_state == false) {
//                tb_status = 0;
//            }
//            switch (tb_status) {
//                case 1:
//                tool_bar_frame.setVisible(true);
//                break;
//                case 0:
//                tool_bar_frame.setVisible(false);
//                break;
//                default:
//                tool_bar_frame.setVisible(true);
//            }
//        }
    }//GEN-LAST:event_toolbar_menuitemActionPerformed

    private void statusbar_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusbar_menuitemActionPerformed
        if (evt.getSource().equals(statusbar_menuitem)) {
            boolean stb_state = statusbar_menuitem.isSelected();
            int stb_status = 1; //default value
            if (stb_state == true) {
                stb_status = 1;
            }
            if (stb_state == false) {
                stb_status = 0;
            }
            switch (stb_status) {
                case 1:
                    footer.setVisible(true);
                    break;
                case 0:
                    footer.setVisible(false);
                    break;
                default:
                    footer.setVisible(true);
            }
        }
    }//GEN-LAST:event_statusbar_menuitemActionPerformed

    private void login_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menuitemActionPerformed
//        if (lo == null) {
//            lo = new login();
//            lo.setVisible(true);
//        }
    }//GEN-LAST:event_login_menuitemActionPerformed

    private void logout_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuitemActionPerformed
//        if (lo == null) {
//            lo = new login();
//            int logoutconfirm = JOptionPane.showConfirmDialog(this, "Are you sure do you want to Logout?", "Logout confirm", YES_NO_OPTION, QUESTION_MESSAGE);
//            if (logoutconfirm == JOptionPane.YES_OPTION) {
//                JOptionPane.showMessageDialog(null, "Logout sucessfully");
//                lo.SetCurrentSession(false);
//            }
//        }
    }//GEN-LAST:event_logout_menuitemActionPerformed

    private void preference_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preference_menuitemActionPerformed
//        option o = new option();
//        o.setVisible(true);
    }//GEN-LAST:event_preference_menuitemActionPerformed

    private void help_contents_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_contents_menuitemActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "E:\\Users\\Chukkrit\\OneDrive\\+ Documents +\\NetBeansProjects\\mergano\\src\\help.html");
        } catch (Exception e) {
            System.out.println("Error detail " + e);
        }
    }//GEN-LAST:event_help_contents_menuitemActionPerformed

    private void online_docs_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_online_docs_menuitemActionPerformed
        openWebsite("https://github.com/Mergano/restaurant/wiki");
    }//GEN-LAST:event_online_docs_menuitemActionPerformed

    private void keyboard_shortcuts_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboard_shortcuts_menuitemActionPerformed
//        keyboard k = new keyboard();
//        k.setVisible(true);
    }//GEN-LAST:event_keyboard_shortcuts_menuitemActionPerformed

    private void report_bug_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_bug_menuitemActionPerformed
        openWebsite("https://github.com/Mergano/restaurant/issues");
    }//GEN-LAST:event_report_bug_menuitemActionPerformed

    private void feedback_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_menuitemActionPerformed
        openWebsite("https://github.com/Mergano/restaurant");
    }//GEN-LAST:event_feedback_menuitemActionPerformed

    private void website_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_website_menuitemActionPerformed
        openWebsite("http://mergano.com");
    }//GEN-LAST:event_website_menuitemActionPerformed

    private void check_for_update_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_for_update_menuitemActionPerformed
        JOptionPane.showMessageDialog(this, "No new update found.", "Check for Updates", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_check_for_update_menuitemActionPerformed

    private void about_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_menuitemActionPerformed
        About a = new About();
        a.setVisible(true);
    }//GEN-LAST:event_about_menuitemActionPerformed

    private void statistic_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistic_btnActionPerformed
        setPane(statistic_pane);
    }//GEN-LAST:event_statistic_btnActionPerformed

    private void billing_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billing_btnActionPerformed
        setPane(billing_pane);
    }//GEN-LAST:event_billing_btnActionPerformed

    private void history_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_btnActionPerformed
        setPane(history_pane);
    }//GEN-LAST:event_history_btnActionPerformed

    private void order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btnActionPerformed
        setPane(order_pane);
    }//GEN-LAST:event_order_btnActionPerformed

    private void table_reserve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_reserve_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_reserve_btnActionPerformed

    private void table_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_btnActionPerformed
        setTable(evt);
    }//GEN-LAST:event_table_btnActionPerformed

    private void openWebsite(String url) {
        try {
            Desktop.getDesktop().browse(new URL(url).toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }

    private void setTable(ActionEvent e) {
        String table_no = ((JButton) e.getSource()).getActionCommand();
        table_no_box.setText(table_no);
    }

    private void setPane(JPanel panel_name) {
        body.removeAll();
        body.add(panel_name);
        body.repaint();
        body.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_menuitem;
    private javax.swing.JMenuItem backup_menuitem;
    private javax.swing.JButton billing_btn;
    private javax.swing.JPanel billing_pane;
    private javax.swing.JPanel body;
    private javax.swing.JMenuItem bookmark_menuitem;
    private javax.swing.JMenuItem check_for_update_menuitem;
    private javax.swing.JButton dashboard_btn;
    private javax.swing.JPanel dashboard_pane;
    private javax.swing.JMenu database_menu;
    private javax.swing.JMenuItem del_db_menuitem;
    private javax.swing.JMenu edit_menu;
    private javax.swing.JMenuItem exit_program;
    private javax.swing.JMenuItem export_csv_menuitem;
    private javax.swing.JMenu export_menuitem;
    private javax.swing.JMenuItem export_sql_menuitem;
    private javax.swing.JMenuItem export_txt_menuitem;
    private javax.swing.JMenuItem feedback_menuitem;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenuItem find_db_menuitem;
    private javax.swing.JMenu folder_menu;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JMenuItem help_contents_menuitem;
    private javax.swing.JMenu help_menu;
    private javax.swing.JButton history_btn;
    private javax.swing.JPanel history_pane;
    private javax.swing.JMenuItem import_csv_menuitem;
    private javax.swing.JMenu import_menuitem;
    private javax.swing.JButton jButton21;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JMenuItem keyboard_shortcuts_menuitem;
    private static javax.swing.JMenuItem login_menuitem;
    private static javax.swing.JMenuItem logout_menuitem;
    private javax.swing.JPanel main_billing_btn_box;
    private javax.swing.JPanel main_dashboard_btn_box;
    private javax.swing.JPanel main_history_btn_box;
    private javax.swing.JPanel main_order_btn_box;
    private javax.swing.JPanel main_reserve_btn_box;
    private javax.swing.JPanel main_statistic_btn_box;
    private javax.swing.JMenuItem new_db_menuitem;
    private javax.swing.JMenuItem online_docs_menuitem;
    private javax.swing.JMenuItem open_menuitem;
    private javax.swing.JButton order_btn;
    private javax.swing.JPanel order_pane;
    private javax.swing.JMenuItem page_setup_menuitem;
    private javax.swing.JMenuItem preference_menuitem;
    private javax.swing.JMenuItem print_menuitem;
    private javax.swing.JMenuItem print_preview_menuitem;
    private javax.swing.JMenuItem printtohtml_menuitem;
    private javax.swing.JPopupMenu property_popup_menu;
    private javax.swing.JMenuItem report_bug_menuitem;
    private javax.swing.JButton reserve_btn;
    private javax.swing.JPanel reserve_pane;
    private javax.swing.JMenuItem save_menuitem;
    private javax.swing.JMenuItem saveas_menuitem;
    private javax.swing.JMenuItem search_menuitem;
    private javax.swing.JButton statistic_btn;
    private javax.swing.JPanel statistic_pane;
    private javax.swing.JMenuItem statistics_menuitem;
    private javax.swing.JCheckBoxMenuItem statusbar_menuitem;
    private javax.swing.JButton table_10_btn;
    private javax.swing.JButton table_11_btn;
    private javax.swing.JButton table_12_btn;
    private javax.swing.JButton table_13_btn;
    private javax.swing.JButton table_14_btn;
    private javax.swing.JButton table_15_btn;
    private javax.swing.JButton table_16_btn;
    private javax.swing.JButton table_17_btn;
    private javax.swing.JButton table_18_btn;
    private javax.swing.JButton table_19_btn;
    private javax.swing.JButton table_1_btn;
    private javax.swing.JButton table_20_btn;
    private javax.swing.JButton table_2_btn;
    private javax.swing.JButton table_3_btn;
    private javax.swing.JButton table_4_btn;
    private javax.swing.JButton table_5_btn;
    private javax.swing.JButton table_6_btn;
    private javax.swing.JButton table_7_btn;
    private javax.swing.JButton table_8_btn;
    private javax.swing.JButton table_9_btn;
    private javax.swing.JMenuItem table_checkout_btn;
    private javax.swing.JMenuItem table_detail_btn;
    private javax.swing.JTextField table_no_box;
    private javax.swing.JMenuItem table_order_btn;
    private javax.swing.JMenuItem table_reserve_btn;
    private javax.swing.JCheckBoxMenuItem toolbar_menuitem;
    private javax.swing.JMenu tools_menu;
    private javax.swing.JMenu view_menu;
    private javax.swing.JMenuItem website_menuitem;
    // End of variables declaration//GEN-END:variables
}
